name: CD (Preview)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 12 * * *'

permissions: read-all

jobs:
  dev_deploy:
    name: Build and Deploy for Preview
    if: ${{ github.repository == 'sws2apps/sws2apps-web' && github.ref == 'refs/heads/main' }}
    environment:
      name: Preview
      url: https://preview-admin.sws2apps.com
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout for release preparation
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          ref: main
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d
        with:
          node-version: current

      - name: Install package dependencies
        run: npm ci

      - name: Build the website
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          VITE_FIREBASE_APIKEY: ${{ secrets.VITE_FIREBASE_APIKEY }}
          VITE_FIREBASE_AUTHDOMAIN: ${{ secrets.VITE_FIREBASE_AUTHDOMAIN }}
          VITE_FIREBASE_PROJECTID: ${{ secrets.VITE_FIREBASE_PROJECTID }}
          VITE_BACKEND_API: ${{ secrets.VITE_BACKEND_API }}

      - name: Check if new version has been generated
        id: check_build
        uses: andstor/file-existence-action@20b4d2e596410855db8f9ca21e96fbe18e12930b
        with:
          files: 'dist'

      - name: Deploy to Firebase
        if: ${{ steps.check_build.outputs.files_exists == 'true' }}
        uses: sws2apps/firebase-deployment@11da74219abba8bc5bc318d8cd403115181e4534
        with:
          workloadIdentityProvider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          serviceAccount: ${{ secrets.SERVICE_ACCOUNT }}
          project: 'dev-sws2apps'
